dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "jojoriveraa"
    token:
      secure: "$sonarcloud"

jdk:
  - oraclejdk8

language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn test -u --all --coverage --ci
  - yarn build
  - sonar-scanner
after_success:
  - yarn codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
